# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='passcode',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
