# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_helper', '0002_room_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='updated_at_date',
        ),
    ]
