# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_helper', '0004_room_characters_vector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('room', 'token')]),
        ),
    ]
